#include "discretization/heat_system.hpp"
#include "mesh/mesh2d.hpp"
#include "physics/thermophysical_properties.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <gtest/gtest.h>
#include <vector>

namespace {

constexpr FluidThermophysicalProperties kFluid{
    .thermal_conductivity = 0.7,
    .density = 1040.0,
    .specific_heat = 4184.0,
};

struct ReferenceCase {
    int code;
    double solid_density;
    double conductivity_at_20_celsius;
    double specific_heat_at_20_celsius;
    double solid_heat_production;
    double temperature;
    double porosity;
    double solid_conductivity;
    double solid_specific_heat;
    double effective_conductivity;
    double volumetric_heat_capacity;
    double effective_heat_production;
};

// Generated by direct calls to the organizer-provided basin_data.py functions.
constexpr std::array kReferenceCases = {
    ReferenceCase{1001, 2200, 6.5, 862.5, 1.2399999999999999e-08, 273.14999999999998, 0,
                  6.925772000220392, 821.96249999999998, 6.925772000220392, 1808317.5,
                  1.2399999999999999e-08},
    ReferenceCase{1001, 2200, 6.5, 862.5, 1.2399999999999999e-08, 373.14999999999998,
                  0.20000000000000001, 5.2519417731748632, 996.05036249999978, 3.5097447254299081,
                  2623320.6379999993, 9.9199999999999988e-09},
    ReferenceCase{1001, 2200, 6.5, 862.5, 1.2399999999999999e-08, 473.14999999999998,
                  0.40000000000000002, 4.2856377965976966, 1127.3979000000002, 2.0761010789834207,
                  3228709.2280000001, 7.4399999999999991e-09},
    ReferenceCase{1002, 2790, 4.2000000000000002, 862.5, 2.9420000000000003e-07, 273.14999999999998,
                  0, 4.4155048208521332, 821.96249999999998, 4.4155048208521332, 2293275.375,
                  2.9420000000000003e-07},
    ReferenceCase{1002, 2790, 4.2000000000000002, 862.5, 2.9420000000000003e-07, 373.14999999999998,
                  0.20000000000000001, 3.5678541949772482, 996.05036249999978, 2.5759966057802308,
                  3093456.4090999993, 2.3536000000000001e-07},
    ReferenceCase{1002, 2790, 4.2000000000000002, 862.5, 2.9420000000000003e-07, 473.14999999999998,
                  0.40000000000000002, 3.0785045839496146, 1127.3979000000002, 1.7023274365633982,
                  3627808.0846000002, 1.7652e-07},
    ReferenceCase{1003, 2720, 3.9500000000000002, 854.10000000000002, 7.0340000000000001e-07,
                  273.14999999999998, 0, 4.1426496926599317, 813.95730000000003, 4.1426496926599317,
                  2213963.8560000001, 7.0340000000000001e-07},
    ReferenceCase{1003, 2720, 3.9500000000000002, 854.10000000000002, 7.0340000000000001e-07,
                  373.14999999999998, 0.20000000000000001, 3.3848011973470729, 986.34969809999984,
                  2.4697110266710438, 3016568.9430655995, 5.6271999999999995e-07},
    ReferenceCase{1003, 2720, 3.9500000000000002, 854.10000000000002, 7.0340000000000001e-07,
                  473.14999999999998, 0.40000000000000002, 2.9472944521400404, 1116.4180248,
                  1.6584154382503595, 3562538.2164735999, 4.2203999999999999e-07},
    ReferenceCase{1004, 2700, 1.6399999999999999, 862.5, 2.0341999999999995e-06, 273.14999999999998,
                  0, 1.6214683081639829, 821.96249999999998, 1.6214683081639829, 2219298.75,
                  2.0341999999999995e-06},
    ReferenceCase{1004, 2700, 1.6399999999999999, 862.5, 2.0341999999999995e-06, 373.14999999999998,
                  0.20000000000000001, 1.6933914992442503, 996.05036249999978, 1.4191408723398289,
                  3021740.7829999994, 1.6273599999999998e-06},
    ReferenceCase{1004, 2700, 1.6399999999999999, 862.5, 2.0341999999999995e-06, 473.14999999999998,
                  0.40000000000000002, 1.7349128342195752, 1127.3979000000002, 1.2067180581875308,
                  3566928.5980000002, 1.2205199999999997e-06},
    ReferenceCase{1005, 2720, 2.0499999999999998, 908.5, 9.6069999999999997e-07, 273.14999999999998,
                  0, 2.0689507183991944, 865.80049999999994, 2.0689507183991944, 2354977.3599999999,
                  9.6069999999999997e-07},
    ReferenceCase{1005, 2720, 2.0499999999999998, 908.5, 9.6069999999999997e-07, 373.14999999999998,
                  0.20000000000000001, 1.9935984153577382, 1049.1730484999998, 1.617073469116552,
                  3153272.5535359997, 7.6855999999999999e-07},
    ReferenceCase{1005, 2720, 2.0499999999999998, 908.5, 9.6069999999999997e-07, 473.14999999999998,
                  0.40000000000000002, 1.9500974503872768, 1187.5257880000001, 1.2944134134618419,
                  3678586.0860160002, 5.7641999999999992e-07},
};

void expect_near_reference(const double actual, const double expected) {
    const double tolerance = 5.0e-13 * std::max(1.0, std::abs(expected));
    EXPECT_NEAR(actual, expected, tolerance);
}

LithotypeThermophysicalProperties lithotype_from(const ReferenceCase& reference) {
    return {
        .code = reference.code,
        .solid_density = reference.solid_density,
        .conductivity_at_20_celsius = reference.conductivity_at_20_celsius,
        .specific_heat_at_20_celsius = reference.specific_heat_at_20_celsius,
        .solid_heat_production = reference.solid_heat_production,
    };
}

Mesh2D make_test_mesh() {
    const Mesh2D::Region region = {
        .vertices = {{0.0, 0.0}, {2.0, 0.0}, {2.0, 1.0}, {0.0, 1.0}},
        .edge_kinds = {BoundaryKind::top, BoundaryKind::right, BoundaryKind::bottom,
                       BoundaryKind::left},
        .id = 1,
    };
    return Mesh2D::generate(std::span<const Mesh2D::Region>(&region, 1),
                            {.cell_size = [](Point2D) { return 0.3; },
                             .smoothing_iterations = 1,
                             .make_quadrilateral = false,
                             .diagnostic_vtu = std::nullopt});
}

} // namespace

TEST(ThermophysicalProperties, ConvertsInputUnitsToSi) {
    EXPECT_DOUBLE_EQ(celsius_to_kelvin(20.0), 293.15);
    EXPECT_DOUBLE_EQ(porosity_percent_to_fraction(25.0), 0.25);
    EXPECT_DOUBLE_EQ(microwatts_per_cubic_meter_to_watts_per_cubic_meter(2.5), 2.5e-6);
}

TEST(ThermophysicalProperties, MatchesOrganizerPythonFunctionsForAllLithotypes) {
    for (const ReferenceCase& reference : kReferenceCases) {
        const LithotypeThermophysicalProperties lithotype = lithotype_from(reference);
        expect_near_reference(sekiguchi_thermal_conductivity(reference.temperature,
                                                             lithotype.conductivity_at_20_celsius),
                              reference.solid_conductivity);
        expect_near_reference(
            waples_specific_heat(reference.temperature, lithotype.specific_heat_at_20_celsius),
            reference.solid_specific_heat);

        const EffectiveThermophysicalProperties effective = evaluate_thermophysical_properties(
            reference.temperature, reference.porosity, lithotype, kFluid);
        expect_near_reference(effective.thermal_conductivity, reference.effective_conductivity);
        expect_near_reference(effective.volumetric_heat_capacity,
                              reference.volumetric_heat_capacity);
        expect_near_reference(effective.heat_production, reference.effective_heat_production);
    }
}

TEST(ThermophysicalProperties, EvaluatesPreallocatedCellFields) {
    const std::array lithotypes = {lithotype_from(kReferenceCases[0]),
                                   lithotype_from(kReferenceCases[4]),
                                   lithotype_from(kReferenceCases[8])};
    const std::array<const LithotypeThermophysicalProperties*, 3> cell_lithotypes = {
        &lithotypes[0], &lithotypes[1], &lithotypes[2]};
    const std::array temperatures = {kReferenceCases[0].temperature, kReferenceCases[4].temperature,
                                     kReferenceCases[8].temperature};
    const std::array porosities = {kReferenceCases[0].porosity, kReferenceCases[4].porosity,
                                   kReferenceCases[8].porosity};
    std::array<double, 3> conductivities{};
    std::array<double, 3> heat_capacities{};
    std::array<double, 3> heat_productions{};

    evaluate_thermophysical_property_fields(temperatures, porosities, cell_lithotypes, kFluid,
                                            conductivities, heat_capacities, heat_productions);

    const std::array references = {kReferenceCases[0], kReferenceCases[4], kReferenceCases[8]};
    for (std::size_t index = 0; index < references.size(); ++index) {
        expect_near_reference(conductivities[index], references[index].effective_conductivity);
        expect_near_reference(heat_capacities[index], references[index].volumetric_heat_capacity);
        expect_near_reference(heat_productions[index], references[index].effective_heat_production);
    }
}

TEST(ThermophysicalProperties, SuppliesFieldsToHeatSystem) {
    const Mesh2D mesh = make_test_mesh();
    const LithotypeThermophysicalProperties lithotype = lithotype_from(kReferenceCases[7]);
    const std::size_t cell_count = mesh.cells().size();
    std::vector<double> temperatures(cell_count, 373.15);
    std::vector<double> porosities(cell_count, 0.2);
    std::vector<const LithotypeThermophysicalProperties*> lithotypes(cell_count, &lithotype);
    std::vector<double> conductivities(cell_count);
    std::vector<double> heat_capacities(cell_count);
    std::vector<double> heat_productions(cell_count);
    evaluate_thermophysical_property_fields(temperatures, porosities, lithotypes, kFluid,
                                            conductivities, heat_capacities, heat_productions);

    const HeatSystem system(mesh, conductivities, heat_capacities, heat_productions,
                            {.surface_temperature = [](Point2D, double) { return 300.0; },
                             .basal_heat_flux = [](Point2D, double) { return 0.06; }});
    Vector temperature(system.size());
    temperature.set_constant(373.15);
    Vector temperature_derivative(system.size());
    temperature_derivative.set_zero();
    Vector residual;
    system.assemble_residual(0.0, temperature, temperature_derivative, residual);
    SparseMatrix matrix(system.size(), system.size(), SparseStorageOrder::csc);
    system.assemble_matrix(NonlinearMethod::picard, 0.0, temperature, temperature_derivative, 1.0,
                           matrix);

    EXPECT_TRUE(residual.all_finite());
    EXPECT_TRUE(matrix.is_compressed());
    EXPECT_GT(matrix.nonzero_count(), system.size());
}
