name: CI Build & Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker environment
        run: docker build -t heat-env .

      - name: Build C++ Project inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace heat-env bash -c "
            cmake --preset release && \
            cmake --build --preset release
          "

      - name: Run Executable
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace heat-env bash -c "
            ./build/release/heat_solver
          "
